# Generated by Django 4.0.4 on 2022-05-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Исполнитель')),
                ('country', models.CharField(max_length=32, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('CD', 'CD'), ('2xCD', '2xCD'), ('CD Digipak', 'CD Digipak'), ('2xCD Digipak', '2xCD Digipak'), ('DVD', 'DVD'), ('2xDVD', '2xDVD'), ('DVD Digipak', 'DVD Digipak'), ('2xDVD Digipak', '2xDVD Digipak')], default='CD', max_length=16, verbose_name='Формат')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Лейбл',
                'verbose_name_plural': 'Лейблы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=128, verbose_name='Альбом')),
                ('year', models.CharField(max_length=4)),
                ('license_year', models.CharField(blank=True, max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.artist')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.itemtype')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='main.label')),
                ('licensed_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.label')),
            ],
        ),
    ]
